### ISSUE TITLE
Link to Github pages is broken

### ISSUE THREAD

**Issue by kevinawoo** [ondrajz/go-callvis#172]
The link the the Github pages is broken here:
<kbd>![screenshot 2024-02-01 at 13 12 27](https://github.com/ondrajz/go-callvis/assets/3469532/b4453879-97e1-4a2c-b6d4-7cd85a200d56)
</kbd>

It should be pointed to https://ondrajz.github.io/go-callvis/

**Comment by ondrajz** [comment]
Thanks fixed.
