### ISSUE TITLE
 unable to find program 'dot', please install it or check your PATH

### ISSUE THREAD

**Issue by frankqwang** [ondrajz/go-callvis#65]
2020/06/11 11:08:10 http serving at http://localhost:7878
2020/06/11 11:08:10 converting dot to svg..
2020/06/11 11:08:10 unable to find program 'dot', please install it or check your PATH

**Comment by rxpd** [comment]
> 2020/06/11 11:08:10 http serving at http://localhost:7878
> 2020/06/11 11:08:10 converting dot to svg..
> 2020/06/11 11:08:10 unable to find program 'dot', please install it or check your PATH

try install [graphviz](http://www.graphviz.org/download/)

**Comment by ofabry** [comment]
You need to install [Graphviz](http://www.graphviz.org/download/).


[README#Requirements](https://github.com/ofabry/go-callvis/blob/master/README.md#requirements).
