### ISSUE TITLE
remove cgo dependency to allow for cross-compilation

### ISSUE THREAD

**Issue by yashbhutwala** [ondrajz/go-callvis#73]

**Comment by kroppt** [comment]
A workaround for this is to use v0.6.0, which does not depend on cgo. However, you will probably still need graphviz.

**Comment by ofabry** [comment]
Suggestion from @kroppt can work as workaround, but I think this should be resolved by making the cgo optional. This could be done by adding two implementations for graphviz rendering, one that uses cgo library and contains `// +build cgo` and the other as a fallback using the system graphviz tool for rendering graph and contains `// +build !cgo`.

**Comment by ondrajz** [comment]
This was fixed in #118
